spring:
  datasource:
    name: hadoop1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.22.178:3306/springboot?useUnicode=true&characterEncoding-utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: hadoop1
    password: hadoop
    #type: com.mysql.cj.jdbc.MysqlXADataSource
    #filters: stat
    #maxActive: 20
    #initialSize: 1
    #maxWait: 6000
    #minIdle: 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  
info:123456778
